# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2af636f8ddc2f353eed615bff8e9ed8c1f1276e10a88b34350f7a322901a038c1ebcfa9b3e3ff01c0890c027226b3bed448aba544d9fc5d479db45d9e319a4c

test:
  secret_key_base: cbe31a566cbea87090b33a638c03d08fdb12342eb252d51d6010fb9caa9b6c553a1237ef535323177d6084b47907838cdb9974d856b8468b6c763fd6fe1daf89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
